{% set name = "pytorch-forecasting" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytorch_forecasting/pytorch_forecasting-{{ version }}.tar.gz
  sha256: 1966e4eb0c3accd5eedde03dac8bdc8ebbc4ffe8109a911434593805158da0d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=1.0.5
  run:
    - pytorch-lightning >=0.10.0
    - optuna >=2.0.0
    - python >=3.7
    - pandas >=1.1.0
    - scikit-learn >=0.23.0
    - scipy >=1.5.2
    - cloudpickle >=1.5.0
    - statsmodels >=0.11.0
    - pytorch >=1.4
    - matplotlib-base >=3.3.1

test:
  imports:
    - pytorch_forecasting
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/jdb78/pytorch-forecasting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Timeseries forecasting with PyTorch
  description: |
    PyTorch Forecasting is a timeseries forecasting package for PyTorch build on PyTorch Lightning.
    It provides timeseries datasets and dataloaders, various ways to normalize variables
    and a number of neural networks for forecasting. The package is tightly integrated with tensorboard
    for logging.
  doc_url: https://pytorch-forecasting.readthedocs.io/
  dev_url: https://github.com/jdb78/pytorch-forecasting

extra:
  recipe-maintainers:
    - jdb78
