{% set name = "pytorch-forecasting" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytorch_forecasting/pytorch_forecasting-{{ version }}.tar.gz
  sha256: 41e5449c4abb54e54bd431408943f5be602b0d0e05973c04aef7d409062cdd78

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9,<3.13
    - setuptools >=1.0.5
  run:
    - lightning >=2.0.0,<3.0.0
    - optuna >=3.1.0,<5.0.0
    - pandas >=1.3.0,<3.0.0
    - python >=3.9
    - scikit-learn >=1.2,<2.0
    - scipy >=1.8,<2.0
    - statsmodels
    - pytorch >=2.0.0,!=2.0.1,<3.0.0
    - matplotlib
    - numpy <=3.0.0
    - cpflows
    - optuna-integration
    - pytorch_optimizer >=2.5.1,<4.0.0

test:
  imports:
    - pytorch_forecasting
  requires:
    - pip

about:
  home: https://github.com/jdb78/pytorch-forecasting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Timeseries forecasting with PyTorch
  description: |
    PyTorch Forecasting is a timeseries forecasting package for PyTorch build on PyTorch Lightning.
    It provides timeseries datasets and dataloaders, various ways to normalize variables
    and a number of neural networks for forecasting. The package is tightly integrated with tensorboard
    for logging.
  doc_url: https://pytorch-forecasting.readthedocs.io/
  dev_url: https://github.com/jdb78/pytorch-forecasting

extra:
  recipe-maintainers:
    - fkiraly
    - jdb78
