{% set name = "pytorch-forecasting" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytorch_forecasting/pytorch_forecasting-{{ version }}.tar.gz
  sha256: 582eafe0d395a57a2c1426d06e16cd36bc9485402b576ee0f2bf6069f58e87ea

build:
  noarch: python
  number: 0

outputs:
  - name: pytorch-forecasting
    requirements:
      host:
        - pip
        - python >=3.9,<3.13
        - setuptools >=70
      run:
        - python >=3.9
        - numpy <=3.0.0
        - torch >=2.0.0,!=2.0.1,<3.0.0
        - lightning >=2.0.0,<3.0.0
        - scipy >=1.8,<2.0
        - pandas >=1.3.0,<3.0.0
        - scikit-learn >=1.2,<2.0

    test:
      imports:
        - pytorch_forecasting
      requires:
        - pip
        - python >=3.9

  - name: pytorch-forecasting-all-extras
    requirements:
      run:
        - python
        - {{ pin_subpackage("pytorch-forecasting", max_pin='x.x.x') }}
        - optuna >=3.1.0,<5.0.0
        - statsmodels
        - matplotlib-base
        - optuna-integration

    test:
      imports:
        - pytorch_forecasting
      requires:
        - pip
        - python >=3.9

about:
  home: https://github.com/jdb78/pytorch-forecasting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Timeseries forecasting with PyTorch
  description: |
    PyTorch Forecasting is a timeseries forecasting package for PyTorch build on PyTorch Lightning.
    It provides timeseries datasets and dataloaders, various ways to normalize variables
    and a number of neural networks for forecasting. The package is tightly integrated with tensorboard
    for logging.
  doc_url: https://pytorch-forecasting.readthedocs.io/
  dev_url: https://github.com/jdb78/pytorch-forecasting

extra:
  recipe-maintainers:
    - yarnabrina
    - benheid
    - fkiraly
    - jdb78
