{% set name = "pytorch-forecasting" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytorch_forecasting/pytorch_forecasting-{{ version }}.tar.gz
  sha256: d82bf05a506e224baa7eaedf0e75faac52b46a894e7200df7337677df217b1d8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10,<3.15
    - setuptools >=70
  run:
    - python >=3.10
    - lightning >=2.0.0,<3.0.0
    - pandas >=1.3.0,<3.0.0
    - scikit-learn >=1.2,<2.0
    - scipy >=1.8,<2.0
    - pytorch >=2.0.0,!=2.0.1,<3.0.0
    - numpy <=3.0.0
    - scikit-base < 0.14.0

test:
  imports:
    - pytorch_forecasting
  requires:
    - pip
    - python >=3.10

about:
  home: https://github.com/jdb78/pytorch-forecasting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Timeseries forecasting with PyTorch
  description: |
    PyTorch Forecasting is a timeseries forecasting package for PyTorch build on PyTorch Lightning.
    It provides timeseries datasets and dataloaders, various ways to normalize variables
    and a number of neural networks for forecasting. The package is tightly integrated with tensorboard
    for logging.
  doc_url: https://pytorch-forecasting.readthedocs.io/
  dev_url: https://github.com/jdb78/pytorch-forecasting

extra:
  recipe-maintainers:
    - pranavbhatp
    - phoeenniixx
    - yarnabrina
    - benheid
    - fkiraly
    - jdb78
